POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Ram",
    "number": "12345"
}

###

DELETE http://localhost:3001/api/persons/6375fe334b2ee388351dca52 HTTP/1.1

###

GET http://localhost:3001/info HTTP/1.1

###

PUT http://localhost:3001/api/persons/6376021906b6f1f402b57d0b HTTP/1.1
Content-Type: application/json

{
    "name": "Ram",
    "number": "12345"
}